name: OST trigger

on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  pull-requests: write

jobs:
  trigger-ost:
    uses: oVirt/ovirt-system-tests/.github/workflows/ost.yaml@ost_on_gh
    secrets: inherit